(module
  (table 2 funcref)
  (type $$___1_0 (func (param i32)))
  (type $$___2_0 (func (param i32) (param i32)))
  (elem (i32.const 0) $$___object___init__)
  (elem (i32.const 1) $$___A_add)
  (func $$___object___init__ (param $self i32)
    (; Variable declarations ;)
    (; Body ;))
  (func $$___A_add (param $self i32) (param $x i32)
    (; Variable declarations ;)
    (; Body ;))
  (func (export "_start") 
    (local $$___IMPL_RET i32)
    (; Variable declarations ;)
    (; Set up the VTBL ;)
    (; Body ;)))
