(module
  (func $f (result i32)
	(local $x i32)
	  (i32.const 0)
	  (local.tee $x)
	  (i32.const 1)
	  (i32.add)
	  (local.tee $x)
	  (i32.const 2)
	  (i32.add)
	  (local.tee $x)
	  (i32.const 3)
	  (i32.add)
	  (local.tee $x)))
