(module
  (table 2 funcref)
  (type $$___1_0 (func (param i32)))
  (type $$___2_0 (func (param i32) (param i32)))
  (elem (i32.const 0) $$___object___init__)
  (elem (i32.const 1) $$___A_add)
  (func $$___object___init__ (param $self i32)
    (; Variable declarations ;)
    (; Body ;))
  (func $$___A_add (param $self i32) (param $x i32) (result i32)
    (i32.const 0)
    (block $a
      (i32.const 0)
      (local.set $x)
      (local.get $self)
      (local.get $x)
      (i32.add)
      (local.set $x))
	(i32.const 2)
	(i32.mul)
    (; Variable declarations ;)
    (; Body ;))
  (func (export "_start") (param $x i32) (result i32)
    (local $$___IMPL_RET i32)
	(local $y i32)
	(i32.const 3)
	(i32.const 0)
	(i32.sub)
	(i32.const 2)
	(i32.add)
	(local.set $x)
	(i32.const -2)
	(local.get $x)
	(i32.mul)
	(i32.const 4)
	(i32.const 10)
	(i32.add)
	(i32.sub)
	(local.set $y)
	(i32.const 0)
	(i32.const 1)
	(call $$___A_add)
    (; Variable declarations ;)
    (; Set up the VTBL ;)
    (; Body ;)))
